name: build the image and publish on DockerHub

env:
  IMAGENAME: buffertly/telnetris

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: multiarch environment
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --name multibuilder --driver docker-container --bootstrap
        docker buildx use multibuilder
    - name: build and push image
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        docker buildx build --platform linux/arm64/v8,linux/amd64 -t $IMAGENAME:latest --push  .
